### ISSUE TITLE
 Question about the performance reported in the paper

### ISSUE THREAD

**Issue by azhuantou** [AIBluefisher/DoGaussian#2]
Thanks for your nice work!

I have a simple question regarding the performance reported in the paper. 

For example, as for the ''Building'' dataset, there are 1920 training images and 20 testing images.
I would like to ask if the reported performance were tested on these 20 testing images?
Did these 20 images participate in the training?

Looking forward to your reply.

**Comment by AIBluefisher** [comment]
For all datasets, we follow the same settings as in MegaNeRF and all previous counterparts. The test images are not and should not be used during training.

**Comment by azhuantou** [comment]
Thanks for your timely reply! @AIBluefisher 

According to [here](https://github.com/cmusatyalab/mega-nerf/issues/18), it seems that half of test images are used during training for MegaNeRF. So I'm not sure if I understand right. 

Now, I know the setting you used. 
Thanks again!

**Comment by AIBluefisher** [comment]
Thanks for pointing this out. Seems I missed that part in MegaNeRF since I didn't use the code base of MegaNeRF except for evaluating its results. For our method, all 20 test images are excluded without being used for training. For evaluation, all the 20 images are used for MegaNeRF and SwitchNeRF. This does not have any other impact for our results but brings higher metrics for MegaNeRF and SwitchNeRF.

**Comment by azhuantou** [comment]
Thank you for your very detailed answer! My problem has been resolved well!
